# Generated by Django 5.1 on 2024-09-10 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('warehouse', 'Warehouse'), ('driver', 'Driver')], default='client', max_length=10),
        ),
    ]
