version: '3.9'

services:
  server:
    image: nafisazizir/meal-u-${IMAGE_TAG}:latest
    restart: unless-stopped
    ports:
      - "${PORT}:8000"
    env_file:
      - ${ENV_FILE}
    environment:
      - PORT=${PORT}

volumes:
  postgres_data:
