# Generated by Django 5.1 on 2024-09-24 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeNutrition',
            fields=[
                ('recipe_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='community.recipe')),
                ('energy_per_serving', models.DecimalField(decimal_places=2, help_text='in kJ', max_digits=6, null=True)),
                ('protein_per_serving', models.DecimalField(decimal_places=2, help_text='in grams', max_digits=6, null=True)),
                ('fat_total_per_serving', models.DecimalField(decimal_places=2, help_text='in grams', max_digits=6, null=True)),
                ('carbohydrate_per_serving', models.DecimalField(decimal_places=2, help_text='in grams', max_digits=6, null=True)),
            ],
        ),
    ]
