# Generated by Django 5.1 on 2024-09-11 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='measurement_size',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_per_measurement',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='groceries.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='PreparationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ingredient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='preparation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='community.preparationtype'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeingredient',
            unique_together={('recipe', 'ingredient', 'preparation_type')},
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
    ]
