# Generated by Django 5.1 on 2024-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealkitrecipe',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
