# Generated by Django 5.1 on 2024-10-06 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0003_alter_mealkitrecipe_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="mealkit",
            name="monetize",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="monetize",
            field=models.BooleanField(default=False),
        ),
    ]
