# Generated by Django 5.1 on 2024-09-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_ingredient_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
