# Generated by Django 5.1 on 2024-09-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_ingredient_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
