# Generated by Django 5.1 on 2024-09-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_alter_recipe_photo'),
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeDietaryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.dietarydetail')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipe')),
            ],
            options={
                'unique_together': {('recipe', 'dietary_details')},
            },
        ),
    ]
