# Generated by Django 5.1 on 2024-09-14 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_recipedietarydetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealkit',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
