# Generated by Django 5.1 on 2024-09-14 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_mealkitdietarydetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealkit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealkit',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealkit',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
