# Generated by Django 5.1 on 2024-09-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_remove_recipe_photo_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealkit',
            name='photo',
        ),
        migrations.AddField(
            model_name='mealkit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mealkits/'),
        ),
    ]
