# Generated by Django 5.1.1 on 2024-10-11 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualPreparationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPreparationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.individualpreparationtype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.product')),
            ],
        ),
    ]
