# Generated by Django 5.1 on 2024-09-10 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dietarydetail',
            name='description',
        ),
    ]
