# Generated by Django 5.1 on 2024-09-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_remove_nutrition_calories_remove_nutrition_carb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='measurement_size',
            field=models.DecimalField(decimal_places=2, help_text='Size of the measurement unit (e.g., 100 for 100g)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price_per_measurement',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Price for the given measurement size', max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit_size',
            field=models.DecimalField(decimal_places=2, help_text='Size of the product', max_digits=6),
        ),
    ]
