# Generated by Django 5.1 on 2024-10-05 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_alter_mealkitrecipe_quantity'),
        ('groceries', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('is_from_mealkit', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipe')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_recipes', to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'recipe', 'is_from_mealkit')},
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.product')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartMealKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mealkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mealkit')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_mealkits', to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'mealkit')},
            },
        ),
        migrations.CreateModel(
            name='CartIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('recipe_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipeingredient')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_ingredients', to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'recipe_ingredient')},
            },
        ),
    ]
