# Generated by Django 5.1.1 on 2024-10-12 04:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0002_initial'),
        ('groceries', '0001_initial'),
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartMealKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mealkit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mealkit')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'mealkit')},
            },
        ),
        migrations.CreateModel(
            name='CartRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('mealkit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartmealkit')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipe')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'recipe', 'mealkit')},
            },
        ),
        migrations.CreateModel(
            name='CartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.product')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CartIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.ingredient')),
                ('preparation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.preparationtype')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartrecipe')),
                ('user_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart')),
            ],
            options={
                'unique_together': {('user_cart', 'recipe', 'ingredient', 'preparation_type')},
            },
        ),
    ]
