# Generated by Django 5.1 on 2024-10-05 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('community', '0003_alter_mealkitrecipe_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartrecipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartrecipe',
            name='meal_kit_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_recipes', to='community.mealkitrecipe'),
        ),
        migrations.AlterUniqueTogether(
            name='cartrecipe',
            unique_together={('user_cart', 'recipe', 'meal_kit_recipe')},
        ),
    ]
