# Generated by Django 5.1 on 2024-10-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartrecipe_unique_together_and_more'),
        ('community', '0003_alter_mealkitrecipe_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartingredient',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartingredient',
            name='cart_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_ingredients', to='cart.cartrecipe'),
        ),
        migrations.AlterUniqueTogether(
            name='cartingredient',
            unique_together={('user_cart', 'recipe_ingredient', 'cart_recipe')},
        ),
    ]
