# Generated by Django 5.1.1 on 2024-10-06 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('community', '0003_alter_mealkitrecipe_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartingredient',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='cartrecipe',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartingredient',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cart.cartrecipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartrecipe',
            name='mealkit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartmealkit'),
        ),
        migrations.AlterField(
            model_name='cartingredient',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart'),
        ),
        migrations.AlterField(
            model_name='cartmealkit',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart'),
        ),
        migrations.AlterField(
            model_name='cartrecipe',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.usercart'),
        ),
        migrations.AlterUniqueTogether(
            name='cartingredient',
            unique_together={('user_cart', 'recipe_ingredient', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='cartrecipe',
            unique_together={('user_cart', 'recipe', 'mealkit')},
        ),
        migrations.CreateModel(
            name='MealKitRecipeCartRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_meal_kit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartmealkit')),
                ('cart_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cartrecipe')),
            ],
            options={
                'unique_together': {('cart_meal_kit', 'cart_recipe')},
            },
        ),
    ]
