# Generated by Django 5.1 on 2024-09-10 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('groceries', '0001_initial'),
        ('orders', '0001_initial'),
        ('user_auth', '0003_employee_employeeroles_deliverycouriers_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydetails',
            name='user_delivery_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userdeliverylocation'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='delivery_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.deliverydetails'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='delivery_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.deliverystatus'),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='delivery_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.deliverytimeslot'),
        ),
        migrations.AddField(
            model_name='lockers',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_auth.deliverycouriers'),
        ),
        migrations.AddField(
            model_name='lockers',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.deliverylocation'),
        ),
        migrations.AddField(
            model_name='orderingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.ingredients'),
        ),
        migrations.AddField(
            model_name='ordermealkits',
            name='mealkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mealkits'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.userpaymentmethod'),
        ),
        migrations.AddField(
            model_name='orderrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipes'),
        ),
        migrations.AddField(
            model_name='orderrecipes',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='ordermealkits',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orderingredients',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='deliveries',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.orderstatuses'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.paymentstatus'),
        ),
        migrations.AddField(
            model_name='usercartingredients',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groceries.ingredients'),
        ),
        migrations.AddField(
            model_name='usercartingredients',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.usercart'),
        ),
        migrations.AddField(
            model_name='usercartmealkits',
            name='mealkit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.mealkits'),
        ),
        migrations.AddField(
            model_name='usercartmealkits',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.usercart'),
        ),
        migrations.AddField(
            model_name='usercartrecipes',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.recipes'),
        ),
        migrations.AddField(
            model_name='usercartrecipes',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.usercart'),
        ),
        migrations.AlterUniqueTogether(
            name='orderrecipes',
            unique_together={('order', 'recipe')},
        ),
        migrations.AlterUniqueTogether(
            name='ordermealkits',
            unique_together={('order', 'mealkit')},
        ),
        migrations.AlterUniqueTogether(
            name='orderingredients',
            unique_together={('order', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='usercartingredients',
            unique_together={('user_cart', 'ingredient')},
        ),
        migrations.AlterUniqueTogether(
            name='usercartmealkits',
            unique_together={('user_cart', 'mealkit')},
        ),
        migrations.AlterUniqueTogether(
            name='usercartrecipes',
            unique_together={('user_cart', 'recipe')},
        ),
    ]
