# Generated by Django 5.1 on 2024-09-25 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lockers',
            name='courier',
        ),
        migrations.RemoveField(
            model_name='lockers',
            name='passcode',
        ),
        migrations.RemoveField(
            model_name='lockers',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.lockers'),
        ),
        migrations.AddField(
            model_name='deliverydetails',
            name='qr_code',
            field=models.TextField(default=1, help_text='String combination of delivery location, delivery time, delivery date, and order.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lockers',
            name='locker_number',
            field=models.CharField(default=1, help_text='Unique locker number for this location', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='passcode',
            field=models.CharField(default=1, help_text='A 4-digit numeric passcode for the order.', max_length=4, validators=[django.core.validators.RegexValidator(message='Passcode must be a 4-digit numeric string.', regex='^\\d{4}$')]),
            preserve_default=False,
        ),
    ]
