# Generated by Django 5.1 on 2024-09-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="delivery_proof_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_proofs/"
            ),
        ),
    ]
