# Generated by Django 5.1 on 2024-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermealkits",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderproducts",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderrecipes",
            name="total",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
