# Generated by Django 5.1 on 2024-10-12 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0002_initial"),
        ("groceries", "0001_initial"),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderingredients",
            name="preparation_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="groceries.preparationtype",
            ),
        ),
        migrations.AlterField(
            model_name="orderingredients",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="community.ingredient"
            ),
        ),
    ]
