# Generated by Django 5.1 on 2024-09-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_ordermealkits_total_alter_orderproducts_total_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverydetails",
            name="user_delivery_location",
        ),
        migrations.AddField(
            model_name="deliverydetails",
            name="delivery_location",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.deliverylocation",
            ),
            preserve_default=False,
        ),
    ]
