# Generated by Django 5.1 on 2024-10-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_orders_delivery_proof_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverylocation",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
