# Generated by Django 5.1 on 2024-09-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_lockers_courier_remove_lockers_passcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="delivery_proof_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="delivery_proofs/"
            ),
        ),
    ]
