# Generated by Django 5.1 on 2024-10-07 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_mealkit_monetize_recipe_monetize"),
        ("orders", "0005_deliverylocation_latitude_deliverylocation_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderIngredients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="community.recipeingredient",
                    ),
                ),
                (
                    "order_recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.orderrecipes",
                    ),
                ),
            ],
        ),
    ]
