# Generated by Django 5.1 on 2024-10-07 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_mealkit_monetize_recipe_monetize"),
        ("orders", "0006_orderingredients"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderrecipes",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderrecipes",
            name="mealkit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.ordermealkits",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderrecipes",
            unique_together={("order", "recipe", "mealkit")},
        ),
    ]
