name: CI/CD

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t nafisazizir/meal-u-prod:latest .
          docker push nafisazizir/meal-u-prod:latest

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: SSH and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd meal-u/
            docker pull nafisazizir/meal-u-prod:latest
            docker-compose down
            docker-compose --env-file .env.prod -f docker-compose.yml up -d
            docker-compose exec server python manage.py migrate
          EOF
